// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrQVb6z3AGnifBs7s4FAJM2BTF6s4EetQ',
    appId: '1:188289635471:android:2dc5a2810950f6bf7c0cfa',
    messagingSenderId: '188289635471',
    projectId: 'bawasiq-171b7',
    storageBucket: 'bawasiq-171b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALT9RYP-E-HhYVbUf18E9jb6JDPwMlzCQ',
    appId: '1:188289635471:ios:7002292f348012087c0cfa',
    messagingSenderId: '188289635471',
    projectId: 'bawasiq-171b7',
    storageBucket: 'bawasiq-171b7.firebasestorage.app',
    androidClientId: '188289635471-14s34uqvcu3t909gn56o1qdsbgoh8g66.apps.googleusercontent.com',
    iosClientId: '188289635471-076ej5k06dhoul3r5f761ll6j1rtbad0.apps.googleusercontent.com',
    iosBundleId: 'com.bawasiq.customer',
  );

}